### ISSUE TITLE
Classificator: Complete Button

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#112]
We want to set everything to "not sure" in the classificator. 

1. Rename "Complete" button --to--> "Save" Button
2. When you open the page, the save button is disabled. 
3. When you change any window to "ambient" or "chainsaw", the save button becomes active. 
4. When you click the save button, the tags are saved to the API. 
5. When you click on the next/previous file button and the save button is active, then we get a pop up asking whether you'd like to save the tags.

**Comment by Starsonic007** [comment]
1:  Rename "Complete" button --to--> "Save" Button --> TEST OK
2: When you open the page, the save button is disabled. --> TEST OK
3: When you change any window to "ambient" or "chainsaw", the save button becomes active. --> TEST OK
4: When you click the save button, the tags are saved to the API.

5: When you click on the next/previous file button and the save button is active, then we get a pop up asking whether you'd like to save the tags. --> TEST Failed. 
@rassokhin-s : 
a: The popup appears even if the save button is still grayed out
b: The popup must be closed so that you can further classify

**Comment by rassokhin-s** [comment]
@Starsonic007 now popup doesn't show if Save button is grayed out.
