### ISSUE TITLE
Simple Phone Player - installation assistance

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#117]
When Topher is up in a tree and installing a guardian, he needs to listen to the latest file from that guardian to verify the installation. 

We'll need a simple player that allows Topher to: 
(1) select a guardian
(2) and then play always and only latest sound file from the guardian
(3) when the latest sound file is played, the player queries the API periodically whether a new file exists and it only continues playing once a new file is available 
(4) We need a time index in local time of latest sound file

Differences to the web player: 
(1) you need to be authenticated as an RFCx user 
(2) The web player doesn't play the latest file right away. It gets the three latest files (1, 2, 3) and plays file 2 . Which works great as we get a stramelined experience without caching. However, here we really need to play the lates file right away. 
(3) The web player was done for continuous streaming. Here we need to always play the latest file - no matter what. That could mean that we have a pause until the latest file is processed and send to us. It could mean that we skip a file. Here, things are really simple, we just want to play the file closest to now. 
(4) If a file is playing and we get a newer file, we will also stop playing the current file and skip to the new file.

**Comment by rassokhin-s** [comment]
Now we have a new tab `Test` at each guardian's page.
![screenshot_stanislav 2017-04-25 18 20 10](https://cloud.githubusercontent.com/assets/2122991/25393358/f09309d6-29e3-11e7-95c3-d94f5ffaec96.png)
At this page we can listen to the latest audio file received by chosen guardian. Request is being sent automatically on tab load.
1) If we received a file, then app opens a player with autoplay and starts a timer with 30 secs interval to request fresh file.
2) if we didn't receive file, then app starts a shorter timer for 10 secs to request new file.

When audio file is played and fresh audio not received, then we start sending request every 10 seconds instead of 30.
User can request file immediately by clicking on `refresh now` button.
If audio file is playing and new one is received, then it automatically switches to new file.

This is how tab looks like on mobile:
![img_0938](https://cloud.githubusercontent.com/assets/2122991/25393625/9f28de94-29e4-11e7-9e52-b427ffee227c.PNG)
