### ISSUE TITLE
Site Picker does not load Cartodb map images

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#3]
see attached screenshot

There does appear to be a JS error in the console, although none of the cartodb map ids are null (even if they were, it should gracefully fall back onto some other behavior to avoid front-end errors)

<img width="1297" alt="console-site-picker-broken" src="https://cloud.githubusercontent.com/assets/1895255/10261417/c11a813e-6996-11e5-9820-e818a9ab5742.png">

**Comment by sweety-wo** [comment]
I tried looking on this issue and seems like something is wrong with generated dist which you using for console.rfcx.org. because i tried checking in my local as well as on generated dist..maps getting loaded each time.. they never get failed...

So what you can do is just regenerate dist and try on it. and if you still have any issue, please assign back to me.

Thanks.

**Comment by topherwhite** [comment]
Works for me, now! Thanks
