### ISSUE TITLE
Classificator after selected file from Model performance

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#65]
Model performance

The Classificator opens after selecting a file. Following the evaluation of the individual sequences I can conclude the review with the "Complete button".
Problem: after pressing the Complete button nothing happens next. What should happen next?

**Comment by rassokhin-s** [comment]
Logically when you open a file from the Performance page, you want to classify only this file (I guess). So logically there is no need for "Next" button, because there is only one file specified for classification. After "Complete" you can go back to Performance page and check new results or do smth else.

If there is a need for "Next" button which will open a random file, just let me know and I'll create this functionality.
Thanks!

**Comment by Starsonic007** [comment]
I think it´s better you have the "Next" Button. You should at least evaluate a new file selection.
And if you want to evaluate only this one file, you can go to the end with the "Complete" button even choose what you want to do next.

**Comment by Starsonic007** [comment]
If its OK for you, you can change the Label from question to enhancement :-)

**Comment by Starsonic007** [comment]
The Next Button is visible and after pushing the Button, a new file is appear  --> TEST OK
