### ISSUE TITLE
"Back" Button in Classificator 

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#66]
Model Performence -> Audio Performance

When I open a file here, the file opens in the Windows Classificator. That fits.
In Classificator there should now be a "back" button, which I can go back to the "Performance Model" section for continue working on the selected model.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296771/167440886377088)

**Comment by rassokhin-s** [comment]
I have a comment/question here:
When we open file for classification, we leave Performance page, so it's being destroyed.
If we want to open last viewed model performance data then, we need open this page again and request fresh data again (it might be changed since we were on this page last time).

Do you want this "Back" button open performance page with predefined Model id and automatically sent requests? Or you want just open Performance page and go through standard flow as always (choose model, press Load button, etc)? In last case I don't see a profit, because we can simply press Performance page link on the left sidebar.

Thanks!

**Comment by Starsonic007** [comment]
After I have listened to the file in Windows classifier, I would like to go back to the "Model Performance page", with the model i recently selected and then listen to an another file from this Model. 
Currently it is quite cumbersome when you first need to click on the Model Performance Button,  and then again selects the model that had previously been open.

**Comment by rassokhin-s** [comment]
After user opens Classificator with audio file, he has a "Back link" near control buttons at page's bottom. When he press this Back link, site opens performance page and loads data for chosen before model.

**Comment by Starsonic007** [comment]
@rassokhin-s , 
I like your solution very well.
I can go back to the model at any time. --> TEST OK.
Thank you for your enhancement.
