### ISSUE TITLE
Classifcation Page: Suggest a Label

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#86]
Currently you can add any label to the classification. We should make sure that when a user enters 'chainsew' instead of 'chainsaw' that this will not generate a new label. We will use a similar technique to Goolge searches 'Did you mean "chainsaw"?' approach. 

All input should be saved with non-capital letters, so the input of "Chainsaw" will be saved as "chainsaw". 
1. We query the /tags/labels endpoint to retrieve all existing labels
2. After each keypress, we 

2.1. Count the number of input characters. When the number is greater or equal to 3, we continue to 2.2.

2.2.  Calculate the Levensthein distance (https://github.com/hiddentao/fast-levenshtein) between the user input non-capitalized ("Chainsaw" -> "chainsaw") and each label from the /tags/labels endpoint 

2.3. We select the label for the entry with the minimum Levensthein distance 

2.4. That selected label is displayed as a 'Did you mean "selected label"' under the input box. The label is a link and when the user clicks it, the selected label replaces the user input.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296771/176289268948677)

**Comment by rassokhin-s** [comment]
Hey @daebwae since we are already loading all labels at point (1), do you think, this task is useful for typing class type at point (2)? I mean - user will not type a classname similar to one of our current types, because he can simply click on a button - all they are downloaded :)
<img width="647" alt="screenshot_stanislav 2016-09-08 18 20 59" src="https://cloud.githubusercontent.com/assets/2122991/18355388/9c88f59a-75f1-11e6-869e-bfcb33cb3930.png">

P.S. I like this task and would like to implement it somewhere, but It might be excess here. Thanks.

**Comment by daebwae** [comment]
Most people will use (1) but in my experience there's always a user (especially if there are a couple of labels) who will type in something very similar but not the same as before. For those users (2) is kinda important.

**Comment by Starsonic007** [comment]
The recognition does not work in large and lower case 

![image](https://cloud.githubusercontent.com/assets/20114180/18524602/50cd485a-7ab9-11e6-829a-36b751414921.png)

**Comment by Starsonic007** [comment]
The arrangement of the individual tabs does not look very nice.

**Comment by Starsonic007** [comment]
It is only possible to write in small letters

**Comment by rassokhin-s** [comment]
1) 
> It is only possible to write in small letters.

Task requirement:
> All input should be saved with non-capital letters, so the input of "Chainsaw" will be saved as "chainsaw".

It is said in the task, that all inputs should be saved in lower-case, that's why I force upper-case to lower-case when user is typing.

2)
> The arrangement of the individual tabs does not look very nice.
I think we might change it to drop-down. I'll work on this.

3) 
> The recognition does not work in large and lower case
To jump from `sad` to `SAD` we need to change 3 letters (`s` -> `S`, `a` -> `A`, `d` -> `D`)
To jump from `sad` to `cat` we need to change 2 letters (`s` -> `c`, `d` -> `t`).
I don't show suggestions which have Levensthein distance >= 3, that's why `sad` -> `SAD` is impossible in this case.
Btw, regarding to point **1)** - there will be no uppercase letters in our classification types, so there will be no issues such jumping from `sad` to `SAD`. I think we can remove these temporary tags from our DB.

**Comment by rassokhin-s** [comment]
@Starsonic007 please take a look at my last comment and reply/close task. Thanks!

**Comment by Starsonic007** [comment]
Hey @rassokhin-s Points 1 and 2 are OK for me.
However with the answer for point 3 I do not agree.
Currently I have in the dropdown "sad" and "cat".
If I now look for "sad", "cat" is suggested to me and when I search for "cat" I get offered "sad". This is a mistake for me.
![image](https://cloud.githubusercontent.com/assets/20114180/19617176/0bf4cf26-982a-11e6-9eda-aaa9e0a3a531.png)
![image](https://cloud.githubusercontent.com/assets/20114180/19617179/39bc4920-982a-11e6-86db-2aee2a9c581e.png)

**Comment by rassokhin-s** [comment]
@Starsonic007 now it should work fine.

**Comment by Starsonic007** [comment]
@rassokhin-s 
Currently we have 2 errors.
1. Large and lower case is now allowed. Should that be so ?
2. At the moment only the word: chainsaw is found in the suggestion selection.

**Comment by Starsonic007** [comment]
![image](https://cloud.githubusercontent.com/assets/20114180/22257765/508a5e10-e25f-11e6-9534-67caf7ac0b48.png)
![image](https://cloud.githubusercontent.com/assets/20114180/22257840/862ab448-e25f-11e6-984b-2ddaadcde801.png)
