### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#92]
https://staging-console.rfcx.org/#/performance/derc
GUID: 0e173f85-1c76-42f5-9a1f-b3927ae35cd6

Currently I have reviewed here just 1 single file. In my review I tested the calculation and discovers an error. In my classification takes a different value to stand at "Precision". The value must be according to my calculation 55.56.
Can you check that, please?

![image](https://cloud.githubusercontent.com/assets/20114180/18523418/6ee8302a-7ab4-11e6-9172-929fbe883bc5.png)

**Comment by rassokhin-s** [comment]
@Starsonic007 I've checked this:
This file was classified by one model two times, that's why we get wrong value. I'll try to figure out what we can do here - maybe update API endpoint.
Thanks for finding this issue!

**Comment by rassokhin-s** [comment]
@Starsonic007 actually, model has classified this file 3 times :)
And here is the calculation issue: model classified only 42 tags (not 45 as it always), that's why you expecting another value.

I also updated our precision and recall endpoints, so now they calculate average value of model confidences if there are more than one classifications for one file.

Please reply or close this issue. Thanks man!
